# Windows Automation Toolkit - Scripts Configuration

[scripts.simple_clipboard]
path = "examples/simple_clipboard.py"
enabled = true
description = "Simple clipboard text manipulation example"
category = "productivity"
subcategory = "text_processing"

[scripts.excel_report_generator]
path = "examples/excel_report_generator.py"
enabled = true
description = "Generate reports from Excel data"
category = "office"
subcategory = "excel"

[scripts.window_organizer]
path = "examples/window_organizer.py"
enabled = true
description = "Organize windows on screen"
category = "system"
subcategory = "window_management"

[scripts.test_execution]
path = "examples/test_execution.py"
enabled = true
description = "Test script for execution testing"
category = "test"
subcategory = "execution"

[scripts.excel_data_processor]
path = "examples/excel_data_processor.py"
enabled = true
description = "Advanced Excel data processing with charts and formatting"
category = "office"
subcategory = "excel"

[scripts.powerpoint_batch_processor]
path = "examples/powerpoint_batch_processor.py"
enabled = true
description = "Batch process PowerPoint presentations"
category = "office"
subcategory = "powerpoint"

[scripts.multi_app_coordinator]
path = "examples/multi_app_coordinator.py"
enabled = true
description = "Coordinate data flow between multiple applications"
category = "automation"
subcategory = "multi_app"

[scripts.advanced_window_manager]
path = "examples/advanced_window_manager.py"
enabled = true
description = "Advanced window management and workspace organization"
category = "system"
subcategory = "window_management"
